name: parallel-jobs

# Controls when the workflow will run

on:

# Triggers the workflow on push or pull request events but only for the "main" branch

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

jobs:

  job1:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - run: echo "Hello world"

  job2:

    runs-on: ubuntu-latest
    needs: [job1]

    steps:

      - uses: actions/checkout@v2

      - run: echo "Hello world"

  job3:

    runs-on: ubuntu-latest

    needs: [job1]

    steps:

      - uses: actions/checkout@v2

      - run: echo "Hello world" 
      
  job4:

    runs-on: ubuntu-latest

    needs: [job1]

    steps:

      - uses: actions/checkout@v2

      - run: echo "Hello world" 
  job5:

    runs-on: ubuntu-latest

    needs: [job2,job3,job4]

    steps:

      - uses: actions/checkout@v2

      - run: echo "Hello world" 
  # test1: 
  #   strategy: 
  #     matrix: 
  #       os: [ubuntu-latest, windows-latest, macos-latest] 
  #   runs-on: $ 
  #   steps: 
  #     - uses: actions/checkout@v2 
  #     - run: echo "hello Test"
  [1:54 PM] Kumar, Shubham
    *********** environment variable *****

  example_matrix:
    strategy:
      matrix:
        version: [10]
        names: ['test1' ,'test2']
    runs-on: ubuntu-latest
    env:
      Day: Friday
      name: Viki
    steps:
      - name: varibles
        run: echo "my name is $name. Day is $Day refrenece of $GITHUB_REF and $github.event  "
      - name: matrixa
        run: echo ${​​{​​matrix.version}​​}​​ 
      - name: test  
        run: echo ${​​{​​matrix.names}​​}​​ 

